---
abstract: 'Perl extension to generate random bytes.'
author:
  - 'John Drago, <jdrago_999@yahoo.com>'
build_requires:
  Statistics::Basic: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bytes-Random
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
